#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MobileAppCA.Resource", IsApplication=true)]

namespace MobileAppCA
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int borrowlendbuttonstyles = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int powerdrill = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int uploadimagedefault = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int wheelbarrow = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060010
			public const int Text = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int btnAddItem = 2131099669;
			
			// aapt resource value: 0x7f060004
			public const int btnBack = 2131099652;
			
			// aapt resource value: 0x7f060017
			public const int btnBorrow = 2131099671;
			
			// aapt resource value: 0x7f06000d
			public const int btnCancel = 2131099661;
			
			// aapt resource value: 0x7f060003
			public const int btnContactLender = 2131099651;
			
			// aapt resource value: 0x7f060018
			public const int btnLend = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int btnSendMessage = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int contentFrame = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int drawerNav = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int imageViewBorrowItem = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int imgItemPhoto = 2131099648;
			
			// aapt resource value: 0x7f060014
			public const int imgUpload = 2131099668;
			
			// aapt resource value: 0x7f060009
			public const int lblBorrowItemDescription = 2131099657;
			
			// aapt resource value: 0x7f060008
			public const int lblBorrowItemName = 2131099656;
			
			// aapt resource value: 0x7f060002
			public const int lblItemDescription = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int lblItemName = 2131099649;
			
			// aapt resource value: 0x7f060016
			public const int lblTitle = 2131099670;
			
			// aapt resource value: 0x7f060011
			public const int lvDrawerNav = 2131099665;
			
			// aapt resource value: 0x7f060006
			public const int lvViewItems = 2131099654;
			
			// aapt resource value: 0x7f060013
			public const int txtEditItemDescription = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int txtEditItemName = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int txtFullname = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int txtMessage = 2131099659;
			
			// aapt resource value: 0x7f060005
			public const int txtSearch = 2131099653;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BorrowItemDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BorrowList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int BorrowListRow = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ContactDialog = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DrawerNavigation = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int LendDialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int addItem = 2130968580;
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040008
			public const int backToList = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int borrow = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int cancel = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int contactLender = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int lend = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int sendMessage = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int title = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
